<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mehmet AKSOY (aksoy.mehmet@metu.edu.tr)">
<meta name="author" content="Sercan AKIL (sercan.akil@metu.edu.tr)">
<meta name="author" content="Deniz Güvenç TEK (deniz.tek@metu.edu.tr)">

<title>Daily Rainfall Modelling in one of the automated-weather observation station in Mugla Province of Türkiye</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Daily Rainfall Modelling_files/libs/clipboard/clipboard.min.js"></script>
<script src="Daily Rainfall Modelling_files/libs/quarto-html/quarto.js"></script>
<script src="Daily Rainfall Modelling_files/libs/quarto-html/popper.min.js"></script>
<script src="Daily Rainfall Modelling_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Daily Rainfall Modelling_files/libs/quarto-html/anchor.min.js"></script>
<link href="Daily Rainfall Modelling_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Daily Rainfall Modelling_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Daily Rainfall Modelling_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Daily Rainfall Modelling_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Daily Rainfall Modelling_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#tree-models-and-regularization" id="toc-tree-models-and-regularization" class="nav-link" data-scroll-target="#tree-models-and-regularization"><span class="header-section-number">1.0.1</span> <strong>Tree Models and Regularization</strong></a></li>
  </ul></li>
  <li><a href="#preliminary-preparations" id="toc-preliminary-preparations" class="nav-link" data-scroll-target="#preliminary-preparations"><span class="header-section-number">2</span> Preliminary Preparations</a>
  <ul class="collapse">
  <li><a href="#uploading-necessary-packages" id="toc-uploading-necessary-packages" class="nav-link" data-scroll-target="#uploading-necessary-packages"><span class="header-section-number">2.0.1</span> Uploading Necessary Packages</a></li>
  <li><a href="#study-location-data" id="toc-study-location-data" class="nav-link" data-scroll-target="#study-location-data"><span class="header-section-number">2.1</span> Study Location &amp; Data</a>
  <ul class="collapse">
  <li><a href="#data-handling" id="toc-data-handling" class="nav-link" data-scroll-target="#data-handling"><span class="header-section-number">2.1.1</span> Data Handling</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics"><span class="header-section-number">2.1.2</span> Descriptive Statistics</a></li>
  <li><a href="#visualization-of-the-data" id="toc-visualization-of-the-data" class="nav-link" data-scroll-target="#visualization-of-the-data"><span class="header-section-number">2.1.3</span> Visualization of the Data</a></li>
  </ul></li>
  <li><a href="#eda-of-the-precipitation" id="toc-eda-of-the-precipitation" class="nav-link" data-scroll-target="#eda-of-the-precipitation"><span class="header-section-number">2.2</span> EDA of the Precipitation</a>
  <ul class="collapse">
  <li><a href="#missing-value" id="toc-missing-value" class="nav-link" data-scroll-target="#missing-value"><span class="header-section-number">2.2.1</span> Missing Value</a></li>
  <li><a href="#time-series-plot-of-the-precipitation-data" id="toc-time-series-plot-of-the-precipitation-data" class="nav-link" data-scroll-target="#time-series-plot-of-the-precipitation-data"><span class="header-section-number">2.2.2</span> Time Series Plot of the Precipitation Data</a></li>
  <li><a href="#seasonality-analyze" id="toc-seasonality-analyze" class="nav-link" data-scroll-target="#seasonality-analyze"><span class="header-section-number">2.2.3</span> Seasonality Analyze</a></li>
  <li><a href="#stationarity-analyze" id="toc-stationarity-analyze" class="nav-link" data-scroll-target="#stationarity-analyze"><span class="header-section-number">2.2.4</span> Stationarity Analyze</a></li>
  <li><a href="#monthly-total-means" id="toc-monthly-total-means" class="nav-link" data-scroll-target="#monthly-total-means"><span class="header-section-number">2.2.5</span> Monthly Total Means</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="header-section-number">3</span> Methodology</a>
  <ul class="collapse">
  <li><a href="#ridge-lasso-regularization" id="toc-ridge-lasso-regularization" class="nav-link" data-scroll-target="#ridge-lasso-regularization"><span class="header-section-number">3.1</span> Ridge &amp; Lasso Regularization</a></li>
  <li><a href="#tree-based-methods" id="toc-tree-based-methods" class="nav-link" data-scroll-target="#tree-based-methods"><span class="header-section-number">3.2</span> Tree-Based Methods</a>
  <ul class="collapse">
  <li><a href="#fitting-regression" id="toc-fitting-regression" class="nav-link" data-scroll-target="#fitting-regression"><span class="header-section-number">3.2.1</span> Fitting Regression</a></li>
  <li><a href="#bagging-and-random-forests" id="toc-bagging-and-random-forests" class="nav-link" data-scroll-target="#bagging-and-random-forests"><span class="header-section-number">3.2.2</span> Bagging and Random Forests</a></li>
  <li><a href="#boosting" id="toc-boosting" class="nav-link" data-scroll-target="#boosting"><span class="header-section-number">3.2.3</span> Boosting</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics"><span class="header-section-number">4</span> Evaluation Metrics</a></li>
  <li><a href="#results-and-conclusion" id="toc-results-and-conclusion" class="nav-link" data-scroll-target="#results-and-conclusion"><span class="header-section-number">5</span> Results and Conclusion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Daily Rainfall Modelling in one of the automated-weather observation station in Mugla Province of Türkiye</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Mehmet AKSOY <em>(aksoy.mehmet@metu.edu.tr)</em> </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Middle East Technical University, Ankara, Türkiye
          </p>
        <p class="affiliation">
            Department of Civil Engineering
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Sercan AKIL <em>(sercan.akil@metu.edu.tr)</em> </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Middle East Technical University, Ankara, Türkiye
          </p>
        <p class="affiliation">
            Geodetic and Geographic Information Technologies
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Deniz Güvenç TEK <em>(deniz.tek@metu.edu.tr)</em> </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Middle East Technical University, Ankara, Türkiye
          </p>
        <p class="affiliation">
            Department of Statistics
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Precipitation is one of the most important meteorological factors that have large impacts on human life and ecosystems worldwide in many ways such as freshwater, irrigation, hydropower production etc. As many authors have indicated that the nature of precipitation shows high variability in terms of both spatial and temporal scales <span class="citation" data-cites="domroes1998a f.2002a mitchell2005a">(<a href="#ref-domroes1998a" role="doc-biblioref">Domroes, Kaviani, and Schaefer 1998</a>; <a href="#ref-f.2002a" role="doc-biblioref">F. 2002</a>; <a href="#ref-mitchell2005a" role="doc-biblioref">Mitchell and Jones 2005</a>)</span>. Therefore, studies on precipitation are very considerable particularly taking into account of climate change effects.</p>
<p>While the ARIMA model is effective for many time series analyses, incorporating seasonality and exogenous variables can significantly enhance its predictive power. However, since ARIMA assumes the time series is stationary, it is necessary to employ a different model for non-stationary data with seasonal patterns.</p>
<p>This is where the SARIMA (Seasonal ARIMA) model comes into play. Similar to the ARIMA model, SARIMA includes additional seasonal autoregressive and moving average components. These seasonal lags correspond to the periodicity of the data (e.g., 12 for monthly data, 24 for hourly data).</p>
<p>SARIMA models facilitate differencing by both seasonal and non-seasonal frequencies<span class="citation" data-cites="kim2010">(<a href="#ref-kim2010" role="doc-biblioref">Kim and Pachepsky 2010</a>)</span>. Identifying the optimal parameters can be streamlined using automated parameter search frameworks such as pmdarima.</p>
<p>Tree decision models are one of the most natural and popular method to model categorical response variables, even these methods can also be used to model continuous responses. In the literature there are many studies that are used tree-based models to predict precipitation amounts, fill the missing data and categorize precipitation types <span class="citation" data-cites="choubin2018 kim2010 englehart2009 wei2019">(<a href="#ref-choubin2018" role="doc-biblioref">Choubin et al. 2018</a>; <a href="#ref-kim2010" role="doc-biblioref">Kim and Pachepsky 2010</a>; <a href="#ref-englehart2009" role="doc-biblioref">Englehart and Douglas 2009</a>; <a href="#ref-wei2019" role="doc-biblioref">Wei, Yan, and Jones 2019</a>)</span>.</p>
<p>Regularization is a technique used to prevent overfitting in statistical models by adding a penalty to the model complexity. In the context of regression models, shrinkage methods are a form of regularization that reduce the size of the coefficients towards zero, effectively shrinking them. This can enhance the model’s generalization to new data by avoiding overfitting.</p>
<p>Two common shrinkage methods are:</p>
<ol type="1">
<li><p><strong>Ridge Regression (L2 regularization)</strong>: Adds a penalty equal to the sum of the squared coefficients.</p></li>
<li><p><strong>Lasso Regression (L1 regularization)</strong>: Adds a penalty equal to the sum of the absolute values of the coefficients.</p></li>
</ol>
<p>The SARIMA (Seasonal Autoregressive Integrated Moving Average) model is a powerful tool for time series forecasting that accounts for both non-seasonal and seasonal components. While SARIMA itself does not directly incorporate regularization methods like those used in regression, regularization can be applied in the context of model selection and parameter estimation to enhance the model’s performance.</p>
<p><strong>Regularization in SARIMA</strong>:</p>
<ul>
<li><p><strong>Parameter Selection</strong>: Automated frameworks such as <strong><code>pmdarima</code></strong> use regularization principles to optimize the selection of SARIMA parameters (p, d, q, P, D, Q, and s). These frameworks often employ criteria like the Akaike Information Criterion (AIC) or Bayesian Information Criterion (BIC), which inherently penalize model complexity to prevent overfitting.</p></li>
<li><p><strong>Ensemble Methods</strong>: Combining multiple SARIMA models with regularization techniques can help in stabilizing the predictions and improving the robustness of the model.</p></li>
</ul>
<section id="tree-models-and-regularization" class="level3" data-number="1.0.1">
<h3 data-number="1.0.1" class="anchored" data-anchor-id="tree-models-and-regularization"><span class="header-section-number">1.0.1</span> <strong>Tree Models and Regularization</strong></h3>
<p>Tree-based models, including Decision Trees, Random Forests, and Gradient Boosting Machines (GBMs), can benefit from regularization techniques to improve their performance and prevent overfitting.</p>
<p><strong>Regularization in Tree Models</strong>:</p>
<ol type="1">
<li><p><strong>Pruning (for Decision Trees)</strong>:</p>
<ul>
<li><p>Reduces the size of the tree by removing sections that provide little power in predicting target variables.</p></li>
<li><p>Can be achieved through cost-complexity pruning which penalizes the tree for having too many branches.</p></li>
</ul></li>
<li><p><strong>Hyperparameter Tuning</strong>:</p>
<ul>
<li><p><strong>Max Depth</strong>: Limiting the depth of the tree to prevent it from growing too complex.</p></li>
<li><p><strong>Min Samples Split</strong>: The minimum number of samples required to split an internal node.</p></li>
<li><p><strong>Min Samples Leaf</strong>: The minimum number of samples required to be at a leaf node.</p></li>
</ul></li>
<li><p><strong>Ensemble Methods</strong>:</p>
<ul>
<li><p><strong>Random Forests</strong>: Aggregate the predictions of multiple decision trees, reducing overfitting through averaging.</p></li>
<li><p><strong>Gradient Boosting</strong>: Sequentially builds trees, where each new tree tries to correct the errors of the previous ones. Regularization in GBM can include:</p>
<ul>
<li><p><strong>Learning Rate</strong>: Controls the contribution of each tree.</p></li>
<li><p><strong>Subsampling</strong>: Uses a subset of data for training each tree.</p></li>
<li><p><strong>L1 and L2 Regularization</strong>: Adds penalties for the complexity of the model.</p></li>
</ul></li>
</ul></li>
<li><p><strong>Regularization Parameters in Gradient Boosting</strong>:</p>
<ul>
<li><p><strong>Shrinkage</strong>: Similar to the learning rate, it scales the contribution of each tree added to the model.</p></li>
<li><p><strong>Column Subsampling</strong>: Reduces overfitting by randomly selecting a subset of features for each tree.</p></li>
</ul></li>
</ol>
<p>This study is focused on daily rainfall modelling for Muğla Province by using meteorological observations.</p>
</section>
</section>
<section id="preliminary-preparations" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Preliminary Preparations</h1>
<section id="uploading-necessary-packages" class="level3" data-number="2.0.1">
<h3 data-number="2.0.1" class="anchored" data-anchor-id="uploading-necessary-packages"><span class="header-section-number">2.0.1</span> Uploading Necessary Packages</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rnaturalearth)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(seasonal)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(grid)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotmo)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tree)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gbm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="study-location-data" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="study-location-data"><span class="header-section-number">2.1</span> Study Location &amp; Data</h2>
<p>In this study, Muğla Province is selected as the study area. This province is located in the southwestern part of Turkey, adjacent to the Mediterranean Sea, and is characterized by a Mediterranean climate with hot, dry summers and mild, wet winters. Muğla’s diverse topography, ranging from coastal areas to mountainous regions, makes it an ideal location for climatic and hydrological studies.</p>
<p>The meteorological station 17292, situated within Muğla Province, is operated by the Turkish State Meteorological Service (TSMS). This station has been consistently providing reliable climatic observations, including temperature, precipitation, humidity, and wind speed data, which are essential for understanding the local climate patterns and trends. The data collected from this station play a crucial role in various research studies, particularly those related to water resources management, agricultural planning, and climate change impact assessments in the region.</p>
<p>The figure below illustrates the precise location of meteorological station 17292 within Muğla Province. This visual representation aids in contextualizing the spatial distribution of climatic data collected and emphasizes the station’s strategic position for capturing representative climatic information for the entire province.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>rnaturalearth<span class="sc">::</span><span class="fu">ne_countries</span>(<span class="at">scale=</span><span class="st">'medium'</span>,<span class="at">returnclass =</span> <span class="st">'sf'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()  <span class="sc">+</span> <span class="fu">geom_sf</span>(<span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fl">28.3668</span>,<span class="at">y=</span><span class="fl">37.2095</span>),<span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">""</span>,<span class="at">y=</span><span class="st">""</span>) <span class="sc">+</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">crs =</span> <span class="fu">st_crs</span>(<span class="dv">4326</span>), <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">31</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">35</span>,<span class="dv">39</span>)) <span class="sc">+</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">'aliceblue'</span>)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom=</span><span class="st">"text"</span>, <span class="at">x=</span><span class="dv">29</span>, <span class="at">y=</span><span class="fl">35.5</span>, <span class="at">label=</span><span class="st">"MEDITERRANEAN SEA"</span>, </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">color=</span><span class="st">"cornflowerblue"</span>, <span class="at">fontface =</span> <span class="st">"bold.italic"</span>, <span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom=</span><span class="st">"text"</span>, <span class="at">x=</span><span class="dv">30</span>, <span class="at">y=</span><span class="fl">38.5</span>, <span class="at">label=</span><span class="st">"TURKIYE"</span>, </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">color=</span><span class="st">"darkgray"</span>, <span class="at">fontface =</span> <span class="st">"bold.italic"</span>, <span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom=</span><span class="st">"text"</span>, <span class="at">x=</span><span class="fl">23.1</span>, <span class="at">y=</span><span class="fl">38.4</span>, <span class="at">label=</span><span class="st">"GREECE"</span>, </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">color=</span><span class="st">"darkgray"</span>, <span class="at">fontface =</span> <span class="st">"bold.italic"</span>, <span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom=</span><span class="st">"text"</span>, <span class="at">x=</span><span class="fl">28.7</span>, <span class="at">y=</span><span class="fl">37.3</span>, <span class="at">label=</span><span class="st">"Mugla Station </span><span class="sc">\n</span><span class="st"> 17292"</span>, </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fontface =</span> <span class="st">"bold.italic"</span>, <span class="at">size=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<section id="data-handling" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="data-handling"><span class="header-section-number">2.1.1</span> Data Handling</h3>
<p>Data period is between 01.01.2009 and 31.12.2023 for Mugla Station (17292). Elevation of the station is 646 meter. Daily precipitation data is used as response variable in modelling. Distinct daily observation variables are used as predictors such as temperature (°C), dew point temperature (°C), sea-level air pressure (mb), cloud coverage (0-8), relative humidity (%), solar exposure (hour), solar radiation (W/m<sup>2</sup>) direction of wind (°) and speed (m/sec).</p>
<p>#complete eksik verileri tamamlama; date kolunu olusturduk vb.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>files<span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="fu">paste0</span>(here<span class="sc">::</span><span class="fu">here</span>(),<span class="st">"/DATA"</span>), <span class="at">pattern =</span> <span class="st">"xlsx"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>listem<span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>missdates<span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(files)) {</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  listem[[i]] <span class="ot">&lt;-</span> <span class="fu">read_excel</span>( <span class="fu">paste0</span>(here<span class="sc">::</span><span class="fu">here</span>(),<span class="st">"/DATA/"</span>, files[i]))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  listem[[i]] <span class="ot">&lt;-</span> listem[[i]][ ,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  listem[[i]]<span class="ot">&lt;-</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    listem[[i]] <span class="sc">|&gt;</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">DATE=</span> <span class="fu">as.Date</span>(<span class="fu">with</span>(listem[[i]], <span class="fu">paste</span>(YEAR,MONTH,DAY,<span class="at">sep=</span><span class="st">"-"</span>)),<span class="st">"%Y-%m-%d"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    tidyr<span class="sc">::</span><span class="fu">complete</span>(<span class="at">DATE =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2009-01-01"</span>),</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>), <span class="at">by =</span> <span class="st">"day"</span>))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  listem[[i]] <span class="ot">&lt;-</span> listem[[i]] [,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>)]</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  missdates[[i]]<span class="ot">&lt;-</span> listem[[i]][<span class="fu">which</span>(<span class="fu">is.na</span>(listem[[i]] [,<span class="dv">2</span>] )),]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>df<span class="ot">&lt;-</span> listem[[<span class="dv">1</span>]]</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">length</span>(files)<span class="sc">-</span><span class="dv">1</span>)) {</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">merge</span>(df, listem[[i<span class="sc">+</span><span class="dv">1</span>]], <span class="at">by =</span> <span class="st">"DATE"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="fu">write.table</span>(df, <span class="st">"merge.txt"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">quote =</span> <span class="cn">FALSE</span>, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="descriptive-statistics" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="descriptive-statistics"><span class="header-section-number">2.1.2</span> Descriptive Statistics</h3>
<ol type="1">
<li><p><strong>Precipitation</strong>: This is any form of water - liquid or solid - that falls from the atmosphere and reaches the ground. It includes rain, snow, sleet, and hail. It is usually measured in millimeters (mm).</p>
<ul>
<li><p>Median: 0.000 mm</p></li>
<li><p>Mean: 3.192 mm</p></li>
<li><p>Maximum: 168.600 mm</p></li>
<li><p>Most days experience no precipitation, but there are occasional instances of heavy rainfall, with a maximum of 168.6 mm.</p></li>
</ul></li>
<li><p><strong>Temperature</strong>: This is a measure of the warmth or coldness of the atmosphere as determined by a thermometer. It is typically reported in degrees Celsius (°C).</p>
<ul>
<li><p>Median (Minimum Temperature): 9.50°C</p></li>
<li><p>Mean (Minimum Temperature): 10.22°C</p></li>
<li><p>Maximum (Minimum Temperature): 27.90°C</p></li>
<li><p>Median (Maximum Temperature): 22.10°C</p></li>
<li><p>Mean (Maximum Temperature): 22.59°C</p></li>
<li><p>Maximum (Maximum Temperature): 41.70°C</p></li>
<li><p>The temperature ranges from cold to hot conditions, with mean temperatures around 10-15°C and maximum temperatures reaching as high as 41.7°C.</p></li>
</ul></li>
<li><p><strong>Dew Point Temperature</strong>: This is the temperature at which air becomes saturated with moisture and dew can form. It is an indicator of the moisture content in the air and is measured in degrees Celsius (°C).</p>
<ul>
<li><p>Median: 4.50°C</p></li>
<li><p>Mean: 7.312°C</p></li>
<li><p>Maximum: 19.90°C</p></li>
<li><p>Dewpoint temperatures indicate varying levels of atmospheric moisture, ranging from dry to humid conditions.</p></li>
</ul></li>
<li><p><strong>Relative Humidity</strong>: This is the amount of moisture in the air compared to what the air can hold at that temperature. It is expressed as a percentage (%).</p>
<ul>
<li><p>Median: 32.00%</p></li>
<li><p>Mean: 37.65%</p></li>
<li><p>Maximum: 100.00%</p></li>
<li><p>Relative humidity values show a wide range of humidity levels, from very dry to highly moist air.</p></li>
</ul></li>
<li><p><strong>Cloudiness</strong>: This refers to the extent of cloud cover in the skyor in descriptive terms such as clear, partly cloudy, mostly cloudy, or overcast.</p>
<ul>
<li><p>Median: 2.000</p></li>
<li><p>Mean: 2.511</p></li>
<li><p>Maximum: 7.600</p></li>
<li><p>Cloudiness varies from clear to cloudy days, with a mean cloudiness value suggesting moderate cloud cover.</p></li>
</ul></li>
<li><p><strong>Wind Speed</strong>: This measures how fast the air is moving. It is typically reported in meters per second (m/s), kilometers per hour (km/h).</p>
<ul>
<li><p>Median: 1.400 m/s</p></li>
<li><p>Mean: 1.418 m/s</p></li>
<li><p>Maximum: 4.700 m/s</p></li>
<li><p>Wind speeds are generally low, with occasional higher speeds recorded.</p></li>
</ul></li>
<li><p><strong>Wind Direction</strong>: This indicates the direction from which the wind is blowing. It is usually expressed in degrees (°) from true north or using compass directions (e.g., N, NE, E).</p>
<ul>
<li><p><strong>Mean</strong>: 209.3 degrees</p></li>
<li><p><strong>Median</strong>: 176.0 degrees</p></li>
<li><p><strong>Minimum</strong>: 1.0 degrees</p></li>
<li><p><strong>Maximum</strong>: 360.0 degrees</p></li>
<li><p><strong>NA’s (Missing Values)</strong>: 111</p></li>
<li><p>These statistics indicate the average, middle, minimum, and maximum wind directions recorded in the dataset, measured in degrees from true north. The presence of missing values (NA’s) suggests that wind direction data is unavailable for some observations.</p></li>
</ul></li>
<li><p><strong>Evapotranspiration</strong>: This is the sum of evaporation from the land surface plus transpiration from plants. It represents the amount of water transferred from the land to the atmosphere. It is usually measured in millimeters (mm).</p>
<ul>
<li><p>Median: 2.500 mm</p></li>
<li><p>Mean: 3.591 mm</p></li>
<li><p>Maximum: 17.700 mm</p></li>
<li><p>Evapotranspiration rates vary, reflecting differences in water loss from soil and plants.</p></li>
</ul></li>
<li><p><strong>Solar Radiation</strong>: This is the energy from the sun received at the Earth’s surface. It is typically measured in watts per square meter (W/m²).</p>
<ul>
<li><p>Median: 4.000 MJ/m²</p></li>
<li><p>Mean: 4.124 MJ/m²</p></li>
<li><p>Maximum: 8.600 MJ/m²</p></li>
<li><p>Solar radiation fluctuates, affecting temperature and other weather parameters.</p></li>
</ul></li>
<li><p><strong>Sun Exposure</strong>: This refers to the duration and intensity of sunlight reaching a particular area. It is often measured in hours per day.</p>
<ul>
<li><p>Median: 4.700 hours</p></li>
<li><p>Mean: 5.138 hours</p></li>
<li><p>Maximum: 12.200 hours</p></li>
<li><p>Sun exposure varies, reflecting differences in daylight duration.</p></li>
</ul></li>
<li><p><strong>Pressure</strong>: This is the force exerted by the atmosphere at a given point. It is usually measured in hectopascals (hPa) or millibars (mb).</p></li>
</ol>
<p>Sea level pressure typically ranges around 1013.25 hectopascals (hPa) or millibars (mb), which is considered the standard atmospheric pressure at sea level. However, actual sea level pressure can vary depending on weather conditions:</p>
<ul>
<li><strong>High Pressure Systems</strong>: These are usually associated with calm and fair weather. Sea level pressures in high-pressure systems typically range from about 1015 hPa to over 1040 hPa.</li>
<li><strong>Low Pressure Systems</strong>: These are associated with stormy and unsettled weather. Sea level pressures in low-pressure systems can drop below 1000 hPa, and in severe storms like hurricanes or typhoons, pressures can drop significantly lower, sometimes reaching around 950 hPa or even lower.
<ul>
<li>Median: 1012.9 hPa</li>
<li>Mean: 1013.3 hPa</li>
<li>Maximum: 1033.5 hPa</li>
<li>Air pressure values fall within typical sea-level pressure ranges, indicating relatively stable atmospheric conditions.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        DATE PRECI MINTEMP MAXTEMP AVETEMP TDEWMIN TDEWMAX AVETDEW MINRELHUM
1 2009-01-01   0.0    -3.6     7.3     1.1   -10.8    -4.4    -6.9        39
2 2009-01-02   0.0    -4.9     7.4     0.4    -5.3     4.2    -0.7        62
3 2009-01-03  13.0     4.3     8.4     6.2     4.4     8.2     6.6        77
4 2009-01-04  22.6     6.8     9.9     7.8     6.7     9.3     7.9        99
5 2009-01-05  27.0     7.2    12.1     8.7     7.1    10.0     8.4        86
6 2009-01-06  25.8     5.3    11.2     7.8     4.8    10.8     6.8        94
  MAXRELHUM AVERELHUM CLOUD PRESSURE AVEWINDD AVEWINDS EVAP RADIATION SUNTIME
1        69      50.2   0.0   1025.7      316      1.9   NA       2.1     3.2
2        96      81.4   4.7   1025.3      126      0.8   NA       1.0     0.2
3        99      96.0   7.0   1020.2      120      1.0   NA       0.3     0.0
4        99      99.0   7.0   1016.3      117      1.2   NA       1.0     0.6
5        99      98.3   7.0   1014.2      116      1.1   NA       1.1     0.5
6        99      98.8   6.9   1011.1       24      1.7   NA       0.6     0.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      DATE                PRECI            MINTEMP         MAXTEMP     
 Min.   :2009-01-01   Min.   :  0.000   Min.   :-8.20   Min.   :-0.90  
 1st Qu.:2012-10-01   1st Qu.:  0.000   1st Qu.: 4.40   1st Qu.:14.60  
 Median :2016-07-01   Median :  0.000   Median : 9.50   Median :22.10  
 Mean   :2016-07-01   Mean   :  3.192   Mean   :10.22   Mean   :22.59  
 3rd Qu.:2020-03-31   3rd Qu.:  0.200   3rd Qu.:16.10   3rd Qu.:30.90  
 Max.   :2023-12-31   Max.   :168.600   Max.   :27.90   Max.   :41.70  
                      NA's   :5                                        
    AVETEMP         TDEWMIN           TDEWMAX          AVETDEW       
 Min.   :-5.30   Min.   :-19.400   Min.   :-13.30   Min.   :-15.400  
 1st Qu.: 8.90   1st Qu.:  0.900   1st Qu.:  7.20   1st Qu.:  4.500  
 Median :14.90   Median :  4.500   Median : 10.30   Median :  7.700  
 Mean   :15.77   Mean   :  4.045   Mean   : 10.07   Mean   :  7.312  
 3rd Qu.:23.10   3rd Qu.:  8.000   3rd Qu.: 13.80   3rd Qu.: 11.100  
 Max.   :34.10   Max.   : 19.100   Max.   : 25.50   Max.   : 19.900  
                                                                     
   MINRELHUM        MAXRELHUM        AVERELHUM         CLOUD      
 Min.   :  0.00   Min.   : 25.00   Min.   :15.00   Min.   :0.000  
 1st Qu.: 22.00   1st Qu.: 71.00   1st Qu.:47.40   1st Qu.:0.700  
 Median : 32.00   Median : 91.00   Median :64.20   Median :2.000  
 Mean   : 37.65   Mean   : 83.66   Mean   :63.92   Mean   :2.511  
 3rd Qu.: 49.00   3rd Qu.: 98.00   3rd Qu.:81.10   3rd Qu.:4.100  
 Max.   :100.00   Max.   :100.00   Max.   :99.30   Max.   :7.600  
                                                                  
    PRESSURE         AVEWINDD        AVEWINDS          EVAP       
 Min.   : 992.9   Min.   :  1.0   Min.   :0.000   Min.   : 0.000  
 1st Qu.:1008.4   1st Qu.:123.0   1st Qu.:1.000   1st Qu.: 0.600  
 Median :1012.9   Median :176.0   Median :1.400   Median : 2.500  
 Mean   :1013.3   Mean   :209.3   Mean   :1.418   Mean   : 3.591  
 3rd Qu.:1017.4   3rd Qu.:315.0   3rd Qu.:1.800   3rd Qu.: 5.300  
 Max.   :1033.5   Max.   :360.0   Max.   :4.700   Max.   :17.700  
                  NA's   :111     NA's   :111     NA's   :2289    
   RADIATION        SUNTIME      
 Min.   :0.000   Min.   : 0.000  
 1st Qu.:1.700   1st Qu.: 1.300  
 Median :4.000   Median : 4.700  
 Mean   :4.124   Mean   : 5.138  
 3rd Qu.:6.400   3rd Qu.: 8.800  
 Max.   :8.600   Max.   :12.200  
 NA's   :377     NA's   :139     </code></pre>
</div>
</div>
</section>
<section id="visualization-of-the-data" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="visualization-of-the-data"><span class="header-section-number">2.1.3</span> Visualization of the Data</h3>
<p>As stated above, relative humidity and cloud cloud coverage should be used as predictors while response is precipitation since the relationship is higher than other variables. However, predictor’s correlation between each other is also high whether positively or negatively. For example, correlation coefficient between cloud coverage and relative humidity is 0.67 or between maximum relative humidity and solar radiation is 0.72. This situation will most likely result in not needing to use many variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>paletr<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#053061"</span>, <span class="st">"#2166AC"</span> ,<span class="st">"#4393C3"</span> ,<span class="st">"#92C5DE"</span> ,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">"#F4A582"</span>, <span class="st">"#D6604D"</span> ,<span class="st">"#B2182B"</span>, <span class="st">"#67001F"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">round</span>(<span class="fu">cor</span>(df[,<span class="dv">2</span><span class="sc">:</span><span class="dv">18</span>], <span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">use =</span> <span class="st">"complete.obs"</span>),<span class="dv">2</span>), </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">method=</span><span class="st">"color"</span>, <span class="at">col=</span>paletr,  </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">type=</span><span class="st">"upper"</span>,  </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">addCoef.col =</span> <span class="st">"white"</span>, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.col=</span><span class="st">"black"</span>,  <span class="at">insig =</span> <span class="st">"blank"</span>, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">diag=</span><span class="cn">FALSE</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>variable_names <span class="ot">&lt;-</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">"Precipitation"</span>, <span class="st">"Minimum_Temperature"</span>, <span class="st">"Maximum_Temperature"</span>, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Average_Temperature"</span>, <span class="st">"Minimum_Dewpoint_Temperature"</span>, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Maximum_Dewpoint_Temperature"</span>, <span class="st">"Average_Dewpoint_Temperature"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Minimum_Relative_Humidity"</span>, <span class="st">"Maximum_Relative_Humidity"</span>, </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Average_Relative_Humidity"</span>, <span class="st">"Cloudiness"</span>, <span class="st">"Air_Pressure"</span>, </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Average_Wind_Direction"</span>, <span class="st">"Average_Wind_Speed"</span>, </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Evapotranspiration"</span>, <span class="st">"Solar_Radiation"</span>, <span class="st">"Sun_Exposure"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df) <span class="ot">&lt;-</span> <span class="fu">append</span>(<span class="st">"Date"</span>, variable_names)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>df_plot<span class="ot">&lt;-</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span>),</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_drop_na =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>df_plot<span class="sc">$</span>name <span class="ot">&lt;-</span> <span class="fu">factor</span>(df_plot<span class="sc">$</span>name, <span class="at">levels =</span> <span class="fu">colnames</span>(df)[<span class="dv">2</span><span class="sc">:</span><span class="dv">18</span>])</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_plot, <span class="fu">aes</span>(<span class="at">x=</span> Date, <span class="at">y=</span>value,<span class="at">color=</span>name)) <span class="sc">+</span> </span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size=</span><span class="fl">0.1</span>) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free_y"</span>, <span class="at">ncol=</span><span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">" "</span>,<span class="at">y=</span><span class="st">" "</span>) <span class="sc">+</span> </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill=</span><span class="st">"white"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_plot, <span class="fu">aes</span>(<span class="at">x=</span> Date, <span class="at">y=</span>value, <span class="at">fill=</span>name, <span class="at">group=</span><span class="fu">year</span>(Date))) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">alpha=</span><span class="fl">0.7</span>) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free_y"</span>, <span class="at">ncol=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">" "</span>,<span class="at">y=</span><span class="st">" "</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill=</span><span class="st">"white"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>In the case of the evapotranspiration dataset, it is imperative to acknowledge the presence of missing values. The temporal variability associated with seasonal patterns, such as temperature fluctuations, precipitation trends, and solar radiation changes, necessitates careful consideration during data analysis and interpretation.</p>
<p>MISSING DATA &amp; EXTRACTION</p>
</section>
</section>
<section id="eda-of-the-precipitation" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="eda-of-the-precipitation"><span class="header-section-number">2.2</span> EDA of the Precipitation</h2>
<section id="missing-value" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="missing-value"><span class="header-section-number">2.2.1</span> Missing Value</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df_pre<span class="ot">=</span>df[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_pre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Date Precipitation
1 2009-01-01           0.0
2 2009-01-02           0.0
3 2009-01-03          13.0
4 2009-01-04          22.6
5 2009-01-05          27.0
6 2009-01-06          25.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculating the number of null values if there is one.</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>pre_null_values<span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(df_pre<span class="sc">$</span>Precipitation))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Number of Null Values in Precipitation Column:"</span>,pre_null_values))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of Null Values in Precipitation Column: 5"</code></pre>
</div>
</div>
</section>
<section id="time-series-plot-of-the-precipitation-data" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="time-series-plot-of-the-precipitation-data"><span class="header-section-number">2.2.2</span> Time Series Plot of the Precipitation Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>missing_date<span class="ot">=</span> df_pre<span class="sc">$</span>Date[<span class="fu">is.na</span>(df_pre<span class="sc">$</span>Precipitation)]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>missing_date</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2012-11-09" "2015-08-03" "2015-08-04" "2015-08-05" "2015-08-06"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Time Series Plot of Precipitation (with Missing Data Highlighted (2009-2024)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_pre, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Precipitation)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">0.5</span>,<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span>  <span class="co"># Continuous line plot</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"orange"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span>  <span class="co">#Trend line</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="sc">!</span><span class="fu">is.na</span>(Precipitation)), <span class="at">size =</span> <span class="dv">1</span>,<span class="at">alpha=</span><span class="fl">0.5</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">data =</span> <span class="fu">subset</span>(df_pre, <span class="fu">is.na</span>(Precipitation)), <span class="fu">aes</span>(<span class="at">label =</span> <span class="st">"NA"</span>, <span class="at">y =</span> <span class="dv">0</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"blue"</span>,<span class="at">size=</span> <span class="dv">3</span>) <span class="sc">+</span>  <span class="co"># Marking NAs</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>)) <span class="sc">+</span>  <span class="co"># Red points for non-missing data</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Time Series Plot of Precipitation Data (2009-2024)"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Precipitation (mm)"</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="co">#Centering the title</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Time Series Plot of Precipitation (with Missing Data Highlighted (2021-2024)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>df_pre_p1<span class="ot">=</span> <span class="fu">filter</span>(df_pre, Date<span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2021-01-01"</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_pre_p1, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> Precipitation)) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Plotting the precipitation data</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="sc">!</span><span class="fu">is.na</span>(Precipitation)), <span class="at">size =</span> <span class="dv">2</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"white"</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"orange"</span>, <span class="st">"red"</span>)) <span class="sc">+</span>  <span class="co"># Use red points to mark non-missing data</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Time Series Plot of Precipitation Data (2021-2024)"</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Precipitation (mm)"</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))  <span class="co"># Improve readability of x-axis labels</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>According to the time series plot of the precipitation, there is no specific long-term trend (orange line) over the years. 4 of the 5 null values are found sequentially and one of them is located in “2012-11-09”. The plot exhibits high volatility and also might be observed some seasonality (clearly observed in plot 2).</p>
</section>
<section id="seasonality-analyze" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="seasonality-analyze"><span class="header-section-number">2.2.3</span> Seasonality Analyze</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Seasonal Decomposition</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Mean Imputation for NA values</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>df_pre1<span class="ot">=</span>df_pre</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>mean_imput<span class="ot">=</span><span class="fu">mean</span>(df_pre1<span class="sc">$</span>Precipitation,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>df_pre1<span class="sc">$</span>Precipitation[<span class="fu">is.na</span>(df_pre1<span class="sc">$</span>Precipitation)]<span class="ot">=</span>mean_imput</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>df_pre_ts<span class="ot">=</span> <span class="fu">ts</span>(df_pre1<span class="sc">$</span>Precipitation, <span class="at">frequency =</span> <span class="dv">365</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>result_stl <span class="ot">&lt;-</span> <span class="fu">stl</span>(df_pre_ts, <span class="at">s.window =</span> <span class="st">"periodic"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(result_stl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ljung_box_result<span class="ot">=</span> <span class="fu">Box.test</span>(df_pre1<span class="sc">$</span>Precipitation, <span class="at">lag=</span> <span class="dv">365</span>, <span class="at">type=</span> <span class="st">"Ljung-Box"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ljung_box_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  df_pre1$Precipitation
X-squared = 4280.5, df = 365, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>Ho: No auto correlation for lags=365</p></li>
<li><p>H1: Some auto correlation for lags=365</p></li>
</ul>
<p>Since the p-value is less than 0.05 we suggest that there is some autocorrelation for lags=365 in Precipitation data which is a strong indication of seasonality. Also, we can clearly observe seasonality in the Seasonality Component plot.</p>
</section>
<section id="stationarity-analyze" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="stationarity-analyze"><span class="header-section-number">2.2.4</span> Stationarity Analyze</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>adf_test<span class="ot">=</span> <span class="fu">adf.test</span>(df_pre1<span class="sc">$</span>Precipitation, <span class="at">alternative =</span> <span class="st">"stationary"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(adf_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  df_pre1$Precipitation
Dickey-Fuller = -12.942, Lag order = 17, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
</div>
<ul>
<li><p>Ho: The time series is non-stationary</p></li>
<li><p>H1: The time series is stationary</p></li>
</ul>
<p>Since our p-value is less than 0.05, it can be concluded that the time series is stationary. That means that the mean, variance and autocorrelation of the series do not change over the years. Since we satisfied the assumption of stationary we can perform Statistical Models as well as Machine Learning Approaches.</p>
</section>
<section id="monthly-total-means" class="level3" data-number="2.2.5">
<h3 data-number="2.2.5" class="anchored" data-anchor-id="monthly-total-means"><span class="header-section-number">2.2.5</span> Monthly Total Means</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month =</span> <span class="fu">month</span>(Date), <span class="at">Year =</span> <span class="fu">year</span>(Date)) <span class="sc">|&gt;</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Month, Year) <span class="sc">|&gt;</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">TotalPrecipitation =</span> <span class="fu">sum</span>(Precipitation, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Month) <span class="sc">|&gt;</span> </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">MeanPrecipitation =</span> <span class="fu">mean</span>(TotalPrecipitation, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(month.name, <span class="at">levels=</span>month.name), </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">y=</span>MeanPrecipitation, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color=</span><span class="st">"navyblue"</span>) <span class="sc">+</span> </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Month"</span>, <span class="at">y =</span> <span class="st">"Precipitation (mm)"</span>) <span class="sc">+</span> </span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"navyblue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="864"></p>
</div>
</div>
</section>
</section>
</section>
<section id="methodology" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methodology</h1>
<section id="ridge-lasso-regularization" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="ridge-lasso-regularization"><span class="header-section-number">3.1</span> Ridge &amp; Lasso Regularization</h2>
<p>Hydrologists use a different time measurement compared to the traditional January-to-December calendar year. For those who model and monitor water movement in the environment, the year starts on October 1st and concludes on September 30th. This period is referred to as a water year. &nbsp;To better understand the numbering system, each month is assigned a numerical value starting from the beginning of the water year. The water year commences in October, thus October is designated as month 1. Consequently, subsequent months follow this sequence, with January being represented as month 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_n<span class="ot">&lt;-</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a> df <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">!</span>Evapotranspiration) <span class="sc">|&gt;</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()  <span class="sc">|&gt;</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Date <span class="sc">&lt;</span> <span class="st">"2023-01-01"</span> ) </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>df_n<span class="sc">$</span>Month<span class="ot">&lt;-</span><span class="fu">ifelse</span>(<span class="fu">month</span>(df_n<span class="sc">$</span>Date)<span class="sc">&gt;=</span><span class="dv">10</span>, </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">month</span>(df_n<span class="sc">$</span>Date)<span class="sc">-</span><span class="dv">9</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">month</span>(df_n<span class="sc">$</span>Date)<span class="sc">+</span><span class="dv">3</span>) </span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(Precipitation <span class="sc">~</span>. , df_n )[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)]</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>y<span class="ot">&lt;-</span> df_n<span class="sc">$</span>Precipitation</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co">#train &lt;- sample(1:nrow(x), nrow(x)*0.8)</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co">#train &lt;- seq(1:4419)</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span>  <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span> <span class="fu">nrow</span>(df_n <span class="sc">|&gt;</span>  <span class="fu">filter</span>(Date <span class="sc">&lt;</span> <span class="st">"2021-01-01"</span> ) ) ) </span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="co">#  RIDGE</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="dv">10</span>, <span class="sc">-</span><span class="dv">2</span>, <span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>ridge.mod <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x[train,], y[train], <span class="at">alpha=</span><span class="dv">0</span>)</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_glmnet</span>(ridge.mod,<span class="at">label=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ridge.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ridge.mod, <span class="at">s=</span><span class="dv">4</span>, <span class="at">newx =</span> x[<span class="sc">-</span>train,])</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( (ridge.pred <span class="sc">-</span> y[<span class="sc">-</span>train])<span class="sc">^</span><span class="dv">2</span> ) <span class="co"># mse</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 73.67183</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ten-fold cross-validation</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>cv.out <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x[train,], y[train], <span class="at">alpha=</span><span class="dv">0</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv.out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>bestlambda <span class="ot">&lt;-</span> cv.out<span class="sc">$</span>lambda.min ; bestlambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4392184</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>ridge.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ridge.mod, <span class="at">s=</span>bestlambda, <span class="at">newx =</span> x[<span class="sc">-</span>train,])</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( (ridge.pred <span class="sc">-</span> y[<span class="sc">-</span>train])<span class="sc">^</span><span class="dv">2</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 69.49357</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>out<span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x[train,], y[train],<span class="at">alpha=</span><span class="dv">0</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(out,<span class="at">type=</span><span class="st">"coefficients"</span>,<span class="at">s=</span>bestlambda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>17 x 1 sparse Matrix of class "dgCMatrix"
                                        s1
(Intercept)                  460.383948666
Minimum_Temperature            0.193974465
Maximum_Temperature            0.056172042
Average_Temperature            0.117465526
Minimum_Dewpoint_Temperature  -0.163577443
Maximum_Dewpoint_Temperature  -0.171714928
Average_Dewpoint_Temperature  -0.287541813
Minimum_Relative_Humidity      0.146014534
Maximum_Relative_Humidity      0.004352156
Average_Relative_Humidity      0.200326824
Cloudiness                     0.061818532
Air_Pressure                  -0.470274958
Average_Wind_Direction        -0.001109263
Average_Wind_Speed             0.577117843
Solar_Radiation                0.007868464
Sun_Exposure                   0.073783086
Month                         -0.154203399</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>pp<span class="ot">&lt;-</span> <span class="fu">predict</span>(out, <span class="at">newx =</span> x[<span class="sc">-</span>train,], <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">s=</span>bestlambda)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>pp2<span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pp <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="dv">0</span>, pp ) <span class="do">## eksi tahminleri sıfıra eşitledik</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y[<span class="sc">-</span>train], pp2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LASSO </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>lasso.mod <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x[train,],y[train], <span class="at">alpha=</span><span class="dv">1</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_glmnet</span>(lasso.mod,<span class="at">label=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>cv.out<span class="ot">=</span><span class="fu">cv.glmnet</span>(x[train ,],y[train],<span class="at">alpha=</span><span class="dv">1</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv.out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-13-5.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>bestlam<span class="ot">=</span>cv.out<span class="sc">$</span>lambda.min ; bestlam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002572511</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lasso.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(lasso.mod, <span class="at">s=</span><span class="dv">4</span>, <span class="at">newx =</span> x[<span class="sc">-</span>train,])</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( (lasso.pred <span class="sc">-</span> y[<span class="sc">-</span>train])<span class="sc">^</span><span class="dv">2</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 94.67503</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>lasso.pred<span class="ot">=</span><span class="fu">predict</span>(lasso.mod,<span class="at">s=</span>bestlam ,<span class="at">newx=</span>x[<span class="sc">-</span>train,])</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>((lasso.pred<span class="sc">-</span>y[<span class="sc">-</span>train])<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68.86685</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>out<span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x[train,], y[train],<span class="at">alpha=</span><span class="dv">1</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(out,<span class="at">type=</span><span class="st">"coefficients"</span>,<span class="at">s=</span>bestlam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>17 x 1 sparse Matrix of class "dgCMatrix"
                                        s1
(Intercept)                   4.450810e+02
Minimum_Temperature           3.009011e-02
Maximum_Temperature           1.588191e-01
Average_Temperature           1.056947e+00
Minimum_Dewpoint_Temperature  7.878162e-02
Maximum_Dewpoint_Temperature -6.202769e-02
Average_Dewpoint_Temperature -1.596246e+00
Minimum_Relative_Humidity     1.253405e-01
Maximum_Relative_Humidity    -2.779996e-02
Average_Relative_Humidity     5.097391e-01
Cloudiness                    1.221550e-01
Air_Pressure                 -4.798007e-01
Average_Wind_Direction       -9.389233e-04
Average_Wind_Speed            9.731138e-01
Solar_Radiation               1.206147e-02
Sun_Exposure                  6.370167e-02
Month                        -1.620786e-01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>pp_2<span class="ot">&lt;-</span> <span class="fu">predict</span>(out, <span class="at">newx =</span> x[<span class="sc">-</span>train,], <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">s=</span>bestlam)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>pp2_2<span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pp_2 <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="dv">0</span>, pp_2 )</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(y[<span class="sc">-</span>train], pp2_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-13-6.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Ridge Regression</li>
</ul>
<p>MSE score is found??77.69??with chosen best lambda??which??is 0.433. According to the plot of the relationship between lambda and coefficients, Average wind speed took the highest coefficient??which??means there is a strong relationship between precipitation. Also, we??penalized??each variable and average wind speed most to avoid bias and overfitting.??Anyway,??we get poor performance on Ridge regression by looking at the plot of actual and predicted values.??Since our precipitation exhibits non-linearity and??it??recognises??rainy days as??spikes??we should think about non-linear solutions like random forest, neural network??etc.</p>
<ul>
<li>Lasso Regression</li>
</ul>
<p>We get similar results when we compare with the results of Ridge regression. Unlike the usual, no variables shrunk towards zero.??This??means each variable is highly correlated and affects the predictor variable with the chosen??of??the optimal??lambda value. Because of??that??can’t we use Lasso regression as a feature selection phase?</p>
<p>Do we need to scale both regreesion and revise the process?</p>
</section>
<section id="tree-based-methods" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="tree-based-methods"><span class="header-section-number">3.2</span> Tree-Based Methods</h2>
<section id="fitting-regression" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="fitting-regression"><span class="header-section-number">3.2.1</span> Fitting Regression</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>df_tree<span class="ot">&lt;-</span> df_n[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>tree.precipitation <span class="ot">&lt;-</span> <span class="fu">tree</span>(Precipitation<span class="sc">~</span>.,df_tree, <span class="at">subset=</span>train)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tree.precipitation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
tree(formula = Precipitation ~ ., data = df_tree, subset = train)
Variables actually used in tree construction:
[1] "Average_Relative_Humidity" "Air_Pressure"             
[3] "Month"                     "Average_Wind_Speed"       
[5] "Maximum_Temperature"      
Number of terminal nodes:  10 
Residual mean deviance:  60.71 = 246500 / 4060 
Distribution of residuals:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-67.910  -0.634  -0.634   0.000  -0.634 121.900 </code></pre>
</div>
</div>
<p>Notice that the output of summary() indicates that only five of the variables have been used in constructing the tree. Relative humidity, air pressure and month variables become the most important ones, as we expected except cloudiness. In the context of a regression tree, the deviance is simply the sum of squared errors for the tree. We now plot the tree.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree.precipitation)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(tree.precipitation,<span class="at">pretty=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>Now we use the cv.tree() function to see whether pruning the tree will improve performance. K-fold cross validation technique is preformed to prune the regression tree. The minimum deviance is available where number of terminal nodes is 4. Thus, we can prune the regression tree from 10 to 4 terminal nodes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>cv.precipitation <span class="ot">&lt;-</span> <span class="fu">cv.tree</span>(tree.precipitation);cv.precipitation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$size
[1] 10  9  8  6  5  4  3  2  1

$dev
[1] 332615.6 327297.8 324067.8 326608.8 324331.5 318885.9 325263.1 334403.1
[9] 417780.2

$k
[1]      -Inf  4555.490  5960.282  6456.620  7022.787  9649.365 14640.983
[8] 27054.240 89204.423

$method
[1] "deviance"

attr(,"class")
[1] "prune"         "tree.sequence"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv.precipitation<span class="sc">$</span>size, cv.precipitation<span class="sc">$</span>dev,</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">'b'</span>, <span class="at">col=</span><span class="st">"dodgerblue"</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">which.min</span>(<span class="fu">rev</span>(cv.precipitation<span class="sc">$</span>dev)), <span class="at">col=</span><span class="st">"firebrick"</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>In this case, the four-node tree is selected by cross-validation. Thus, we can prune the tree, we could do so as follows, using the prune.tree() function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>prune.precipitation <span class="ot">&lt;-</span> <span class="fu">prune.tree</span>(tree.precipitation,<span class="at">best=</span><span class="dv">4</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(prune.precipitation)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(prune.precipitation,<span class="at">pretty=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>In keeping with the cross-validation results, we use the unpruned tree to make predictions on the test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(tree.precipitation,<span class="at">newdata=</span>df_tree[<span class="sc">-</span>train,])</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>df_tree.test <span class="ot">&lt;-</span> df_tree[<span class="sc">-</span>train,<span class="st">"Precipitation"</span>]</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>plot_test<span class="ot">&lt;-</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(yhat, df_tree.test) <span class="sc">|&gt;</span> </span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> yhat, <span class="at">y=</span>df_tree.test)) <span class="sc">+</span> </span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>, <span class="at">alpha=</span><span class="fl">0.5</span>, <span class="at">color=</span><span class="st">"dodgerblue"</span>) <span class="sc">+</span> </span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>() <span class="sc">+</span> </span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Predicted Response"</span>,<span class="at">y=</span><span class="st">"True Response"</span>) <span class="sc">+</span> </span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x=</span><span class="dv">60</span>, <span class="at">y=</span><span class="dv">20</span>, <span class="at">label=</span> </span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>             <span class="fu">paste</span>(<span class="st">"MSE is"</span>,</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>             <span class="fu">round</span>(<span class="fu">mean</span>((yhat <span class="sc">-</span> df_tree.test)<span class="sc">^</span><span class="dv">2</span>),<span class="dv">2</span>)))</span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>plot_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>In other words, the test set MSE associated with the regression tree is 64.19. The square root of the MSE is therefore around 8.01, indicating that this model leads to test predictions that are within around 8.01 mm of the true median precipitation value for the Mugla Station.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>yhat_prune <span class="ot">&lt;-</span><span class="fu">predict</span>(prune.precipitation,<span class="at">newdata=</span>df_tree[<span class="sc">-</span>train,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The MSE and RMSE for pruned tree are estimated as 73.2 and 8.56, respectively. Due to the nature of regression trees the predictions equal to averages of response variables in training data based on embranchment of the tree. In our example, predictions are available for five and 4 variables for unpruned and pruned cases, respectively.</p>
</section>
<section id="bagging-and-random-forests" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="bagging-and-random-forests"><span class="header-section-number">3.2.2</span> Bagging and Random Forests</h3>
<p>Here we apply bagging and random forests to the our data, using the randomForest package in R. Recall that bagging is simply a special case of a random forest with m = p.&nbsp;Therefore, the randomForest() function can be used to perform both random forests and bagging. The argument mtry=16 indicates that all 16 predictors should be considered for each split of the tree.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>bag.precipitation <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Precipitation <span class="sc">~</span>., <span class="at">data=</span>df_tree, <span class="at">subset=</span>train, <span class="at">mtry=</span><span class="dv">16</span>,<span class="at">importance=</span><span class="cn">TRUE</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>bag.precipitation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = Precipitation ~ ., data = df_tree, mtry = 16,      importance = TRUE, subset = train) 
               Type of random forest: regression
                     Number of trees: 500
No. of variables tried at each split: 16

          Mean of squared residuals: 71.12541
                    % Var explained: 30.66</code></pre>
</div>
</div>
<p>The Random Forest model consists of 500 decision trees. MSE on training data for the last tree is estimated as 71.12541. Percentage of variance in the target variable value of 30.66% indicates that the model explains about 30.66% of the variance in precipitation. The explained variance of 30.66% suggests that the model captures about a third of the variability in precipitation based on the provided predictors. This is a moderate level of explanatory power, indicating that while the model is capturing some of the relationships, there is still a significant portion of variability that it doesn’t explain.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>yhat.bag <span class="ot">=</span> <span class="fu">predict</span>(bag.precipitation, <span class="at">newdata=</span>df_tree[<span class="sc">-</span>train,])</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(yhat.bag, df_tree.test) <span class="sc">|&gt;</span> </span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> yhat, <span class="at">y=</span>df_tree.test)) <span class="sc">+</span> </span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>, <span class="at">alpha=</span><span class="fl">0.5</span>, <span class="at">color=</span><span class="st">"dodgerblue"</span>) <span class="sc">+</span> </span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_abline</span>() <span class="sc">+</span> </span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Predicted Response"</span>,<span class="at">y=</span><span class="st">"True Response"</span>) <span class="sc">+</span> </span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x=</span><span class="dv">60</span>, <span class="at">y=</span><span class="dv">20</span>, <span class="at">label=</span> </span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>           <span class="fu">paste</span>(<span class="st">"MSE is"</span>,</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(<span class="fu">mean</span>((yhat.bag <span class="sc">-</span> df_tree.test)<span class="sc">^</span><span class="dv">2</span>),<span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>The test set MSE associated with the bagged regression tree is 60.15, this is almost 20% lower than that achived using an optimally-pruned single tree.</p>
<p>Growing a random forest proceeds in exactly the same way, except that we use a smaller value of the mtry argument. By default, randomForest() uses p/3 variables when building a random forest of regression trees, and p<sup>1/2</sup> variables when building a random forest of classification trees. Here we use mtry = 7</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>rf.precipitation <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Precipitation <span class="sc">~</span>., <span class="at">data=</span>df_tree, <span class="at">subset=</span>train, <span class="at">mtry=</span><span class="dv">7</span>,<span class="at">importance=</span><span class="cn">TRUE</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>yhat.rf <span class="ot">=</span> <span class="fu">predict</span>(rf.precipitation, <span class="at">newdata=</span>df_tree[<span class="sc">-</span>train,])</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>((yhat.rf <span class="sc">-</span> df_tree.test)<span class="sc">^</span><span class="dv">2</span>),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55.59</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(rf.precipitation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               %IncMSE IncNodePurity
Minimum_Temperature          16.160678      14778.44
Maximum_Temperature           9.845887      20956.25
Average_Temperature           9.374431      16525.34
Minimum_Dewpoint_Temperature 13.542117      14001.32
Maximum_Dewpoint_Temperature 15.573700      14343.46
Average_Dewpoint_Temperature 15.028109      14144.06
Minimum_Relative_Humidity     8.076360      45179.71
Maximum_Relative_Humidity    19.352939      18790.17
Average_Relative_Humidity    16.963041      81998.60
Cloudiness                   12.660491      20328.04
Air_Pressure                 24.139181      51233.80
Average_Wind_Direction        5.647770      21234.88
Average_Wind_Speed           10.076902      21711.69
Solar_Radiation               9.785292      15123.42
Sun_Exposure                 10.015703      10597.99
Month                         8.743882      11755.50</code></pre>
</div>
</div>
<p>The test set MSE is 55.59; this indicates that random forests yielded an improvement over bagging in this case. Using the importance() function, we can view the importance of each variable. Two measures of variable importance are reported. The former is based upon the mean decrease of accuracy in predictions on the out of bag samples when a given variable is excluded from the model. The latter is a measure of the total decrease in node impurity that results from splits over that variable, averaged over all trees. In the case of regression trees, the node impurity is measured by the training RSS. Plots of these importance measures can be produced using the varImpPlot() function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(rf.precipitation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="864"></p>
</div>
</div>
<p>The results indicate that across all of the trees considered in the random forest, the air pressure (mb) and the maximum relative humidity (%) are by far the two most important variables.</p>
</section>
<section id="boosting" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="boosting"><span class="header-section-number">3.2.3</span> Boosting</h3>
<p>Here we use the gbm package, and within it the gbm() function, to fit boosted regression trees to the our data set. We run gbm() with the option distribution=“gaussian” since this is a regression problem, shrinkage parameter/learning rate is taken as 0.03. The argument n.trees=5000 indicates that we want 5000 trees, and the option interaction.depth=6 limits the depth of each tree.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>boost.precipitation <span class="ot">=</span> <span class="fu">gbm</span>(Precipitation <span class="sc">~</span>.,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> df_tree[train,],</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">distribution =</span> <span class="st">"gaussian"</span>,</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">shrinkage =</span> .<span class="dv">03</span>,</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">interaction.depth=</span><span class="dv">6</span>,</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">n.trees =</span> <span class="dv">5000</span>)</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boost.precipitation)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Daily-Rainfall-Modelling_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                               rel.inf
Average_Relative_Humidity    23.391199
Air_Pressure                 13.940102
Minimum_Relative_Humidity     7.402162
Average_Wind_Speed            6.965498
Average_Wind_Direction        5.967477
Minimum_Temperature           5.665308
Maximum_Temperature           5.268572
Cloudiness                    4.722548
Solar_Radiation               4.557934
Maximum_Dewpoint_Temperature  3.708303
Average_Temperature           3.433266
Minimum_Dewpoint_Temperature  3.330333
Maximum_Relative_Humidity     3.154003
Average_Dewpoint_Temperature  3.042658
Sun_Exposure                  2.880234
Month                         2.570404</code></pre>
</div>
</div>
<p>We see that average relative humidity and air pressure variables are the most important variables. Now we can use the boosted model to predict daily precipitation on the test data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>yhat.boost <span class="ot">&lt;-</span> <span class="fu">predict</span>(boost.precipitation,<span class="at">newdata=</span>df_tree[<span class="sc">-</span>train,],<span class="at">n.trees=</span><span class="dv">5000</span>,<span class="at">interaction.depth=</span><span class="dv">6</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>((yhat.boost <span class="sc">-</span> df_tree.test)<span class="sc">^</span><span class="dv">2</span>),<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54.74</code></pre>
</div>
</div>
<p>The test MSE of boosted model obtained is 54.74 and it is superior to the test MSE for random forests and bagging.</p>
</section>
</section>
</section>
<section id="evaluation-metrics" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Evaluation Metrics</h1>
</section>
<section id="results-and-conclusion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Results and Conclusion</h1>
<p>Eshel and Farrell <span class="citation" data-cites="eshel2000">(<a href="#ref-eshel2000" role="doc-biblioref">Eshel and Farrell 2000</a>)</span> investigated rainfall variability over Eastern Mediterranean and they showed that rainfall is mostly depend on pressure anomalies. Lower air pressure is mostly related with precipitation since mostly frontal systems brings rainfall over Eastern Mediterranean. These frontal systems also means windy storms which comes from over Mediterranean Sea. Similarly, relative humidity is highly related with precipitation since rainfall formation is much easier in saturated air conditions. As everyone might guess cloud is necessary for rainfall production. By the way, dew point temperature means that how much air should be cooled to be saturated without any moisture addition. Thus, closer dew point temperature and air temperature means highly saturated and vice versa. As stated above, relative humidity, cloud coverage, air pressure, dew point temperature, wind direction, wind speed and temperature should be used as predictors while response is precipitation. However, only relative humidity, air pressure and wind direction parameters are used in our pruned trees. This situation most probably caused because of predictor’s correlation between each other. Correlation matrix of variables is given in Figure 11. As shown in the Figure, some variables are highly correlated with each other whether positive or negative. For example, correlation coefficient between cloud coverage and relative humidity is 0.7 and -0.6 between dew point temperature and air pressure. Thus, using many variables has become unnecessary.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-choubin2018" class="csl-entry" role="listitem">
Choubin, Bahram, Gholamreza Zehtabian, Ali Azareh, Elham Rafiei-Sardooi, Farzaneh Sajedi-Hosseini, and Özgür Kişi. 2018. <span>“Precipitation Forecasting Using Classification and Regression Trees (CART) Model: A Comparative Study of Different Approaches.”</span> <em>Environmental Earth Sciences</em> 77 (8). <a href="https://doi.org/10.1007/s12665-018-7498-z">https://doi.org/10.1007/s12665-018-7498-z</a>.
</div>
<div id="ref-domroes1998a" class="csl-entry" role="listitem">
Domroes, M., M. Kaviani, and D. Schaefer. 1998. <span>“An Analysis of Regional and Intra-Annual Precipitation Variability over Iran Using Multivariate Statistical Methods.”</span> <em>Theoretical and Applied Climatology</em> 61 (3-4): 151–59. <a href="https://doi.org/10.1007/s007040050060">https://doi.org/10.1007/s007040050060</a>.
</div>
<div id="ref-englehart2009" class="csl-entry" role="listitem">
Englehart, Phil J., and Arthur V. Douglas. 2009. <span>“Diagnosing Warm<span>-</span>Season Rainfall Variability in Mexico: A Classification Tree Approach.”</span> <em>International Journal of Climatology</em> 30 (5): 694–704. <a href="https://doi.org/10.1002/joc.1934">https://doi.org/10.1002/joc.1934</a>.
</div>
<div id="ref-eshel2000" class="csl-entry" role="listitem">
Eshel, Gidon, and Brian F. Farrell. 2000. <span>“Mechanisms of Eastern Mediterranean Rainfall Variability.”</span> <em>Journal of the Atmospheric Sciences</em> 57 (19): 3219–32. <a href="https://doi.org/10.1175/1520-0469(2000)057<3219:moemrv>2.0.co;2">https://doi.org/10.1175/1520-0469(2000)057&lt;3219:moemrv&gt;2.0.co;2</a>.
</div>
<div id="ref-f.2002a" class="csl-entry" role="listitem">
F., Giorgi. 2002. <span>“Variability and Trends of Sub-Continental Scale Surface Climate in the Twentieth Century. Part i: Observations.”</span> <em>Climate Dynamics</em> 18 (8): 675–91. <a href="https://doi.org/10.1007/s00382-001-0204-x">https://doi.org/10.1007/s00382-001-0204-x</a>.
</div>
<div id="ref-kim2010" class="csl-entry" role="listitem">
Kim, Jung-Woo, and Yakov A. Pachepsky. 2010. <span>“Reconstructing Missing Daily Precipitation Data Using Regression Trees and Artificial Neural Networks for SWAT Streamflow Simulation.”</span> <em>Journal of Hydrology</em> 394 (3-4): 305–14. <a href="https://doi.org/10.1016/j.jhydrol.2010.09.005">https://doi.org/10.1016/j.jhydrol.2010.09.005</a>.
</div>
<div id="ref-mitchell2005a" class="csl-entry" role="listitem">
Mitchell, Timothy D., and Philip D. Jones. 2005. <span>“An Improved Method of Constructing a Database of Monthly Climate Observations and Associated High-Resolution Grids.”</span> <em>International Journal of Climatology</em> 25 (6): 693–712. <a href="https://doi.org/10.1002/joc.1181">https://doi.org/10.1002/joc.1181</a>.
</div>
<div id="ref-wei2019" class="csl-entry" role="listitem">
Wei, Wenguang, Zhongwei Yan, and Phil D. Jones. 2019. <span>“A Decision<span>-</span>Tree Approach to Seasonal Prediction of Extreme Precipitation in Eastern China.”</span> <em>International Journal of Climatology</em> 40 (1): 255–72. <a href="https://doi.org/10.1002/joc.6207">https://doi.org/10.1002/joc.6207</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>